DateTime error
this error is caused by DateTime settings. please add this to your code

Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are required to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /home2/markewl7/public_html/guildgear/system/library/Hybrid/Logger.php:80 Stack trace: #0 /home2/markewl7/public_html/guildgear/system/library/Hybrid/Logger.php(80): DateTime->__construct() #1 /home2/markewl7/public_html/guildgear/system/library/Hybrid/Endpoint.php(210): Hybrid_Logger::error('Endpoint: Error...') #2 /home2/markewl7/public_html/guildgear/system/library/Hybrid/Endpoint.php(117): Hybrid_Endpoint->authInit() #3 /home2/markewl7/public_html/guildgear/system/library/Hybrid/Endpoint.php(51): Hybrid_Endpoint->processAuthStart() #4 /home2/markewl7/public_htm in /home2/markewl7/public_html/guildgear/system/library/Hybrid/Logger.php on line 80